name: Generovanie EPG a GitHub Pages

on:
  schedule:
    - cron: '30 2 * * *' # Každé ráno o 4:30 nášho času
  workflow_dispatch: # Pre manuálne spustenie

# Pridávame potrebné povolenia pre zápis do repozitára aj priamo na GitHub Pages web
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Stiahnutie repozitára
      uses: actions/checkout@v4

    - name: 🐍 Nastavenie Pythonu
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: ⚙️ Spustenie EPG skriptu
      run: python generator_epg.py

    - name: 💾 Commit a Push epg.json späť do repozitára
      run: |
        git config --global user.name "GitHub Action Bot"
        git config --global user.email "action@github.com"
        git add epg.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Aktualizácia EPG dát"
        git push

    - name: 🛠️ Nastavenie GitHub Pages
      uses: actions/configure-pages@v5

    - name: 📦 Nahratie súborov pre web
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.' # Nahrá celý priečinok vrátane nového epg.json

    - name: 🚀 Publikovanie na GitHub Pages web
      uses: actions/deploy-pages@v4
